server:
  port: 8080
  session:
    timeout: 60

#mysql 
#spring: 
#  datasource: 
#    url: jdbc:mysql://lcoalhost:3306/mp
#    username: root
#    password: 123456
#  aop:
#    proxy-target-class: true

spring: 
  devtools: 
    restart:
      additional-paths:
      - src/main/java
      - src/main/resources
      exclude: WEB-INF/**
    livereload:
      enabled: true
      
     
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db1:
        url: jdbc:mysql://localhost:3306/mp?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #filters: stat,wall,log4j2
      db2:
        url: jdbc:mysql://localhost:3306/mpbak?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #filters: stat,wall,log4j2
 

#log
logging:
  config: classpath:logback.xml
  path: d:/logs


# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:com/gao/mybatis/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.gao.mybatis.entity
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

   


